version: "3"
services:
  nginx:
    image: jamesjan/mynginx:latest
    container_name: mynginx
    restart: always
    network_mode: "bridge"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
