version: "3"
services:
  nginx:
    image: jamesjan/mynginx:latest
    restart: always
    network_mode: "bridge"
    ports:
      - "8000:80"
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
